# Generated by Django 5.2 on 2025-04-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_classified_type_donation_donation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedrecipient',
            name='donor_name',
            field=models.CharField(blank=True, default='Anonymous Donor', max_length=200),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, default='Anonymous Donor', max_length=200),
        ),
    ]
