# Generated by Django 5.2 on 2025-04-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donatedrecipient_donor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
