# Generated by Django 5.2 on 2025-04-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_recipient_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatedrecipient',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donatedrecipient',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipient',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
